version: '3'
services:
  backend:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./capivarasBack:/usr/src/app
    command: bash -c "npm install && npm start"  # Corrigir o comando
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

  frontend:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./capivarasfront:/usr/src/app
    command: bash -c "npm install && npm run serve"  # Corrigir o comando
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge